services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf   
    depends_on:
      - app1
      - app2
    networks:
      - servicosderedes

  app1:
    image: showip:latest 
    networks:
      - servicosderedes

  app2:
    image: showip:latest
    networks:
      - servicosderedes

networks:
  servicosderedes:

