version: '3'
services:
  nginx:
    image: proxy:latest
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - servicosderedes

  app1:
    image: showip:latest 
    networks:
      - servicosderedes

  app2:
    image: showip:latest
    networks:
      - servicosderedes

networks:
  servicosderedes:

