---
- hosts: web
  tasks:
  - name: install and check nginx latest version
    become: true
    apt: 
      name: nginx 
      state: latest
      update_cache: true  
  - name: start nginx
    service:
      name: nginx
      state: started
- hosts: bancodedados
  tasks:
  - name: install and check mysql latest version
    become: true
    apt: 
      name: mysql-server
      state: latest
      update_cache: true  
  - name: start mysql
    service:
      name: mysql
      state: started
