apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  selector:
    app: todolist-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000 
  type: NodePort # Permite acesso externo à aplicação
