apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todolist-ingress
  namespace: todolist
spec:
  ingressClassName: nginx
  rules:
  - host: todolist.local # Substitua pelo seu domínio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todolist-service 
            port:
              number: 80
