services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf   
    depends_on:
      - app
    networks:
      - todolist 

  db:
    image: postgres:latest
    volumes: 
      - ./instance:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=todolist
    networks:
      - todolist

  app:
    image: todolist:postgrecontainer 
    volumes:
      - ./instance:/app/instance
    depends_on:
      - db
    networks:
      - todolist

networks:
  todolist:

